rootLogger = INFO, STDOUT

appender.STDOUT.type = Console
appender.STDOUT.name = STDOUT
appender.STDOUT.layout.type = PatternLayout
appender.STDOUT.layout.pattern = %d{HH:mm:ss} %-5level %logger{36} - %msg%n
